//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObligatorioProg3_Estadio.EstadioWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosEvento", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DatosEvento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ideventoField;
        
        private int idpuertaField;
        
        private int capacidadField;
        
        private double costoField;
        
        private int disponibilidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idevento {
            get {
                return this.ideventoField;
            }
            set {
                if ((this.ideventoField.Equals(value) != true)) {
                    this.ideventoField = value;
                    this.RaisePropertyChanged("idevento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idpuerta {
            get {
                return this.idpuertaField;
            }
            set {
                if ((this.idpuertaField.Equals(value) != true)) {
                    this.idpuertaField = value;
                    this.RaisePropertyChanged("idpuerta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int capacidad {
            get {
                return this.capacidadField;
            }
            set {
                if ((this.capacidadField.Equals(value) != true)) {
                    this.capacidadField = value;
                    this.RaisePropertyChanged("capacidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double costo {
            get {
                return this.costoField;
            }
            set {
                if ((this.costoField.Equals(value) != true)) {
                    this.costoField = value;
                    this.RaisePropertyChanged("costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int disponibilidad {
            get {
                return this.disponibilidadField;
            }
            set {
                if ((this.disponibilidadField.Equals(value) != true)) {
                    this.disponibilidadField = value;
                    this.RaisePropertyChanged("disponibilidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EstadioWebService.ConsultaEstadioWebServiceSoap")]
    public interface ConsultaEstadioWebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ObligatorioProg3_Estadio.EstadioWebService.HelloWorldResponse HelloWorld(ObligatorioProg3_Estadio.EstadioWebService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ObligatorioProg3_Estadio.EstadioWebService.HelloWorldResponse> HelloWorldAsync(ObligatorioProg3_Estadio.EstadioWebService.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento deResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/de", ReplyAction="*")]
        ObligatorioProg3_Estadio.EstadioWebService.deResponse de(ObligatorioProg3_Estadio.EstadioWebService.deRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/de", ReplyAction="*")]
        System.Threading.Tasks.Task<ObligatorioProg3_Estadio.EstadioWebService.deResponse> deAsync(ObligatorioProg3_Estadio.EstadioWebService.deRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Disponibilidad", ReplyAction="*")]
        int Disponibilidad(int idevento, int idpuerta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Disponibilidad", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DisponibilidadAsync(int idevento, int idpuerta);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ObligatorioProg3_Estadio.EstadioWebService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ObligatorioProg3_Estadio.EstadioWebService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ObligatorioProg3_Estadio.EstadioWebService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ObligatorioProg3_Estadio.EstadioWebService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="de", Namespace="http://tempuri.org/", Order=0)]
        public ObligatorioProg3_Estadio.EstadioWebService.deRequestBody Body;
        
        public deRequest() {
        }
        
        public deRequest(ObligatorioProg3_Estadio.EstadioWebService.deRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idevento;
        
        public deRequestBody() {
        }
        
        public deRequestBody(int idevento) {
            this.idevento = idevento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deResponse", Namespace="http://tempuri.org/", Order=0)]
        public ObligatorioProg3_Estadio.EstadioWebService.deResponseBody Body;
        
        public deResponse() {
        }
        
        public deResponse(ObligatorioProg3_Estadio.EstadioWebService.deResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ObligatorioProg3_Estadio.EstadioWebService.DatosEvento[] deResult;
        
        public deResponseBody() {
        }
        
        public deResponseBody(ObligatorioProg3_Estadio.EstadioWebService.DatosEvento[] deResult) {
            this.deResult = deResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultaEstadioWebServiceSoapChannel : ObligatorioProg3_Estadio.EstadioWebService.ConsultaEstadioWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaEstadioWebServiceSoapClient : System.ServiceModel.ClientBase<ObligatorioProg3_Estadio.EstadioWebService.ConsultaEstadioWebServiceSoap>, ObligatorioProg3_Estadio.EstadioWebService.ConsultaEstadioWebServiceSoap {
        
        public ConsultaEstadioWebServiceSoapClient() {
        }
        
        public ConsultaEstadioWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaEstadioWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaEstadioWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaEstadioWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ObligatorioProg3_Estadio.EstadioWebService.HelloWorldResponse ObligatorioProg3_Estadio.EstadioWebService.ConsultaEstadioWebServiceSoap.HelloWorld(ObligatorioProg3_Estadio.EstadioWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ObligatorioProg3_Estadio.EstadioWebService.HelloWorldRequest inValue = new ObligatorioProg3_Estadio.EstadioWebService.HelloWorldRequest();
            inValue.Body = new ObligatorioProg3_Estadio.EstadioWebService.HelloWorldRequestBody();
            ObligatorioProg3_Estadio.EstadioWebService.HelloWorldResponse retVal = ((ObligatorioProg3_Estadio.EstadioWebService.ConsultaEstadioWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ObligatorioProg3_Estadio.EstadioWebService.HelloWorldResponse> ObligatorioProg3_Estadio.EstadioWebService.ConsultaEstadioWebServiceSoap.HelloWorldAsync(ObligatorioProg3_Estadio.EstadioWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ObligatorioProg3_Estadio.EstadioWebService.HelloWorldResponse> HelloWorldAsync() {
            ObligatorioProg3_Estadio.EstadioWebService.HelloWorldRequest inValue = new ObligatorioProg3_Estadio.EstadioWebService.HelloWorldRequest();
            inValue.Body = new ObligatorioProg3_Estadio.EstadioWebService.HelloWorldRequestBody();
            return ((ObligatorioProg3_Estadio.EstadioWebService.ConsultaEstadioWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ObligatorioProg3_Estadio.EstadioWebService.deResponse ObligatorioProg3_Estadio.EstadioWebService.ConsultaEstadioWebServiceSoap.de(ObligatorioProg3_Estadio.EstadioWebService.deRequest request) {
            return base.Channel.de(request);
        }
        
        public ObligatorioProg3_Estadio.EstadioWebService.DatosEvento[] de(int idevento) {
            ObligatorioProg3_Estadio.EstadioWebService.deRequest inValue = new ObligatorioProg3_Estadio.EstadioWebService.deRequest();
            inValue.Body = new ObligatorioProg3_Estadio.EstadioWebService.deRequestBody();
            inValue.Body.idevento = idevento;
            ObligatorioProg3_Estadio.EstadioWebService.deResponse retVal = ((ObligatorioProg3_Estadio.EstadioWebService.ConsultaEstadioWebServiceSoap)(this)).de(inValue);
            return retVal.Body.deResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ObligatorioProg3_Estadio.EstadioWebService.deResponse> ObligatorioProg3_Estadio.EstadioWebService.ConsultaEstadioWebServiceSoap.deAsync(ObligatorioProg3_Estadio.EstadioWebService.deRequest request) {
            return base.Channel.deAsync(request);
        }
        
        public System.Threading.Tasks.Task<ObligatorioProg3_Estadio.EstadioWebService.deResponse> deAsync(int idevento) {
            ObligatorioProg3_Estadio.EstadioWebService.deRequest inValue = new ObligatorioProg3_Estadio.EstadioWebService.deRequest();
            inValue.Body = new ObligatorioProg3_Estadio.EstadioWebService.deRequestBody();
            inValue.Body.idevento = idevento;
            return ((ObligatorioProg3_Estadio.EstadioWebService.ConsultaEstadioWebServiceSoap)(this)).deAsync(inValue);
        }
        
        public int Disponibilidad(int idevento, int idpuerta) {
            return base.Channel.Disponibilidad(idevento, idpuerta);
        }
        
        public System.Threading.Tasks.Task<int> DisponibilidadAsync(int idevento, int idpuerta) {
            return base.Channel.DisponibilidadAsync(idevento, idpuerta);
        }
    }
}
